services:
  graphql:
    build:
      context: .
      target: production
      dockerfile: dockerfile
    extends:
      service: graphql
      file: ./compose.base.yml
    container_name: stocky
    restart: unless-stopped
    # Use curl to check if the application is healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
