services:
  elysia:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    env_file: ".env"
    ports:
      - "3000:3000"
    networks:
      - graphql-network
    depends_on:
      # Wait for the database to be healthy
      postgres:
        condition: service_healthy
      # Wait for migrations to complete
      migrations:
        condition: service_completed_successfully
  
  migrations:
    build:
      context: .
      target: development
      dockerfile: dockerfile
    # Do not restart the migrations container
    restart: "no"
    env_file: ".env"
    networks:
      - graphql-network
    entrypoint: ["bunx", "--bun", "prisma", "migrate", "deploy"]
    depends_on:
      # Wait for the database to be healthy
      postgres:
        condition: service_healthy
