services:
  stocky:
    env_file: ".env"
    depends_on:
      # Wait for the database to be healthy
      postgres:
        condition: service_healthy
      # Wait for migrations to complete
      migrations:
        condition: service_completed_successfully
    networks:
      - stocky-net
  
  migrations:
    env_file: ".env"
    depends_on:
      # Wait for the database to be healthy
      postgres:
        condition: service_healthy
    networks:
     - stocky-net
