services:
  graphql:
    build:
      context: .
      target: development
      dockerfile: dockerfile
    extends:
      service: graphql
      file: ./common.yml
    container_name: stocky
    restart: unless-stopped
    env_file: ".env"

  postgres:
    extends:
      service: postgres
      file: ./common.yml
    container_name: postgres
    restart: unless-stopped
    env_file: ".env"
